name: Deploy Firestore Rules on merge

on:
  push:
    branches:
      - master
    paths:
      - firestore.indexes.json
      - firestore.rules

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,firestore:indexes --project default
        env:
          GCP_SA_KEY: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SLIPIT2_97E5C }}'
