name: Deploy Firestore Rules on merge

on:
  push:
    branches:
      - master
    paths:
      - firestore.indexes.json
      - firestore.rules
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx firebase deploy --only firestore:rules,firestore:indexes --project default --token ${{ secrets.FIREBASE_TOKEN }}
